### PR TITLE
Tidy up some pieces around wellcomecollection.org subdomains

### PR DESCRIPTION
**Pull request by alexwlchan**
## What's changing and why?

Subdomain behaviour should be easier to define; in particular CNAME records for third-party services and redirecting subdomains to wellcomecollection.org.

This is a precursor to an actual breaking change, which will be a separate PR.

## `terraform plan` diff

n/a

### CODE REVIEW

**Review by jamieparkinson — APPROVED** [review]
drives me mad that this stuff is in a directory called `cloudfront`

**Comment by alexwlchan** [comment]
> drives me mad that this stuff is in a directory called `CloudFront`

Happy to take suggestions for alternative names! I’d be tempted to split it into a separate repo also.

dns-infrastructure?
wellcomecollection.org-dns?

**Comment by jamieparkinson** [comment]
iirc the different subdirs of `cloudfront` variously contain cloudfront and non-cloudfront things? +1 for `dns-infrastructure`, though

**Comment by alexwlchan** [comment]
I've opened https://github.com/wellcomecollection/platform-infrastructure/issues/325 to track moving this into a separate repo.

**Pull request merged**
